default: &default
  adapter: postgresql
  encoding: unicode
  database: smash
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: postgres
  password:
  host: postgres

test:
  adapter: sqlite3
  database: ":memory:"

production:
  url: <%= ENV['DATABASE_URL'] %>
